"""
export_swiggy_cookies.py
========================
Run this script ONCE to capture your real Swiggy session cookies.

It opens a visible Chrome browser to swiggy.com/instamart.
  1. Log in to Swiggy as you normally would (OTP, Google, etc.)
  2. Browse to any Instamart search so the location is set.
  3. Press ENTER in this terminal when you see products loading.

The script will save your cookies to  swiggy_cookies.json
The main scraper will automatically load them on the next search.
"""
import asyncio
import json
import sys
from pathlib import Path
from playwright.async_api import async_playwright

COOKIE_FILE = Path(__file__).parent / "swiggy_cookies.json"
USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)
STEALTH_ARGS = [
    "--disable-blink-features=AutomationControlled",
    "--no-sandbox",
    "--disable-infobars",
    "--window-size=1280,900",
    "--start-maximized",
]


async def main():
    print("=" * 60)
    print("  Swiggy Cookie Exporter")
    print("=" * 60)
    print()
    print("Opening Swiggy Instamart in a browser window...")
    print("Steps:")
    print("  1. Log in to your Swiggy account (OTP / Google)")
    print("  2. Allow location or manually set it to your area")
    print("  3. Search for any product (e.g. 'maggi') to confirm")
    print("     products are loading properly")
    print("  4. Come back here and press ENTER")
    print()

    async with async_playwright() as pw:
        browser = await pw.chromium.launch(
            headless=False,
            args=STEALTH_ARGS,
        )
        context = await browser.new_context(
            user_agent=USER_AGENT,
            locale="en-IN",
            viewport={"width": 1280, "height": 900},
        )
        await context.add_init_script(
            "Object.defineProperty(navigator, 'webdriver', {get: () => undefined})"
        )

        page = await context.new_page()
        await page.goto(
            "https://www.swiggy.com/instamart",
            timeout=30000,
            wait_until="domcontentloaded",
        )

        print("Browser opened. Complete the login steps above.")
        print()
        print("Press ENTER here once products are visible in the browser: ", end="", flush=True)

        # Wait for user to press Enter (non-blocking friendly approach)
        loop = asyncio.get_event_loop()
        await loop.run_in_executor(None, sys.stdin.readline)

        print()
        print("Capturing cookies...")
        cookies = await context.cookies()

        # Also grab localStorage values for userLocation
        loc_keys = ["userLocation", "selectedLocation", "userDetails"]
        local_storage = {}
        try:
            for key in loc_keys:
                val = await page.evaluate(f"localStorage.getItem('{key}')")
                if val:
                    local_storage[key] = val
        except Exception:
            pass

        current_url = page.url

        await context.close()
        await browser.close()

    if not cookies:
        print("❌ No cookies captured. Did the browser open correctly?")
        return

    # Filter to only Swiggy-relevant cookies
    swiggy_cookies = [c for c in cookies if "swiggy" in c.get("domain", "")]

    output = {
        "cookies": swiggy_cookies,
        "local_storage": local_storage,
        "captured_from_url": current_url,
        "note": "Generated by export_swiggy_cookies.py — do not commit to git",
    }

    COOKIE_FILE.write_text(json.dumps(output, indent=2))

    print(f"✅ Saved {len(swiggy_cookies)} cookies to: {COOKIE_FILE}")
    print()
    print("Cookie names captured:")
    for c in swiggy_cookies:
        print(f"  · {c['name']}")
    print()
    print("localStorage keys captured:", list(local_storage.keys()) or ["(none)"])
    print()
    print("Done! Restart the app server and try a search — Instamart")
    print("should now return live data using your session.")


asyncio.run(main())
